/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.10 */
package parser;

public interface ParserTreeConstants
{
  public int JJTINPUT = 0;
  public int JJTVOID = 1;
  public int JJTEQUIV = 2;
  public int JJTIMPL = 3;
  public int JJTOR = 4;
  public int JJTAND = 5;
  public int JJTBINARYTEMP = 6;
  public int JJTUNARY = 7;
  public int JJTATOM = 8;


  public String[] jjtNodeName = {
    "Input",
    "void",
    "Equiv",
    "Impl",
    "Or",
    "And",
    "BinaryTemp",
    "Unary",
    "Atom",
  };


}
/* JavaCC - OriginalChecksum=d1af9a7f3436e3d57d0b17893383f3b3 (do not edit this line) */
