/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 5;
  /** RegularExpression Id. */
  int RPAREN = 6;
  /** RegularExpression Id. */
  int AND = 7;
  /** RegularExpression Id. */
  int OR = 8;
  /** RegularExpression Id. */
  int IMPL = 9;
  /** RegularExpression Id. */
  int EQUIV = 10;
  /** RegularExpression Id. */
  int ATOM = 11;
  /** RegularExpression Id. */
  int TRUE = 12;
  /** RegularExpression Id. */
  int FALSE = 13;
  /** RegularExpression Id. */
  int UNARY = 14;
  /** RegularExpression Id. */
  int NOT = 15;
  /** RegularExpression Id. */
  int ONCE = 16;
  /** RegularExpression Id. */
  int HIST = 17;
  /** RegularExpression Id. */
  int YEST = 18;
  /** RegularExpression Id. */
  int FIN = 19;
  /** RegularExpression Id. */
  int GLOB = 20;
  /** RegularExpression Id. */
  int NEXT = 21;
  /** RegularExpression Id. */
  int BINARYTEMP = 22;
  /** RegularExpression Id. */
  int UNTIL = 23;
  /** RegularExpression Id. */
  int SINCE = 24;
  /** RegularExpression Id. */
  int UNLESS = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"&\"",
    "\"|\"",
    "\"->\"",
    "\"<->\"",
    "<ATOM>",
    "\"true\"",
    "\"false\"",
    "<UNARY>",
    "\"!\"",
    "\"O\"",
    "\"H\"",
    "\"Y\"",
    "\"F\"",
    "\"G\"",
    "\"X\"",
    "<BINARYTEMP>",
    "\"U\"",
    "\"S\"",
    "\"W\"",
  };

}
